export default {
    list_banks: [
        {name: 'Vietcombank', logo: 'Areas/Mobile/Content/Images/vi-vn/icon_bkcard_1001.jpg'},
        {name: 'Sacombank', logo: 'Areas/Mobile/Content/Images/vi-vn/icon_bkcard_1002.jpg'},
        {name: 'ACB', logo: 'Areas/Mobile/Content/Images/vi-vn/icon_bkcard_1003.jpg'},
        {name: 'Techcombank', logo: 'Areas/Mobile/Content/Images/vi-vn/icon_bkcard_1004.jpg'},
        {name: 'DongABank', logo: 'Areas/Mobile/Content/Images/vi-vn/icon_bkcard_1005.jpg'},
        {name: 'VietinBank', logo: 'Areas/Mobile/Content/Images/vi-vn/icon_bkcard_1006.jpg'},
        {name: 'BIDV', logo: 'Areas/Mobile/Content/Images/vi-vn/icon_bkcard_1007.jpg'},
        {name: 'EXIMBANK', logo: 'Areas/Mobile/Content/Images/vi-vn/icon_bkcard_1008.jpg'},
        {name: 'VIB', logo: 'Areas/Mobile/Content/Images/vi-vn/icon_bkcard_1009.jpg'},
        {name: 'OCENBANK', logo: 'Areas/Mobile/Content/Images/vi-vn/icon_bkcard_1010.jpg'},
        {name: 'HDBank', logo: 'Areas/Mobile/Content/Images/vi-vn/icon_bkcard_1011.jpg'},
        {name: 'SCB', logo: 'Areas/Mobile/Content/Images/vi-vn/icon_bkcard_1012.jpg'},
        {name: 'NAM A Bank', logo: 'Areas/Mobile/Content/Images/vi-vn/icon_bkcard_1013.jpg'},
        {name: 'Viet A Bank', logo: 'Areas/Mobile/Content/Images/vi-vn/icon_bkcard_1014.jpg'},
        {name: 'SeABank', logo: 'Areas/Mobile/Content/Images/vi-vn/icon_bkcard_1015.jpg'},
        {name: 'OCB', logo: 'Areas/Mobile/Content/Images/vi-vn/icon_bkcard_1016.jpg'},
        {name: 'IVB', logo: 'Areas/Mobile/Content/Images/vi-vn/icon_bkcard_1017.jpg'},
        {name: 'VPBank', logo: 'Areas/Mobile/Content/Images/vi-vn/icon_bkcard_1018.jpg'},
        {name: 'TPBank', logo: 'Areas/Mobile/Content/Images/vi-vn/icon_bkcard_1019.jpg'},
        {name: 'PVcomBank', logo: 'Areas/Mobile/Content/Images/vi-vn/icon_bkcard_1020.jpg'},
        {name: 'NCB', logo: 'Areas/Mobile/Content/Images/vi-vn/icon_bkcard_1021.jpg'},
        {name: 'GP Bank', logo: 'Areas/Mobile/Content/Images/vi-vn/icon_bkcard_1022.jpg'},
        {name: 'Bac A Bank', logo: 'Areas/Mobile/Content/Images/vi-vn/icon_bkcard_1023.jpg'},
        {name: 'PG Bank', logo: 'Areas/Mobile/Content/Images/vi-vn/icon_bkcard_1024.jpg'},
        {name: 'MariTime Bank', logo: 'Areas/Mobile/Content/Images/vi-vn/icon_bkcard_1025.jpg'},
        {name: 'VietBank', logo: 'Areas/Mobile/Content/Images/vi-vn/icon_bkcard_1026.jpg'},
        {name: 'HSBC', logo: 'Areas/Mobile/Content/Images/vi-vn/icon_bkcard_1027.jpg'},
        {name: 'MB Bank', logo: 'Areas/Mobile/Content/Images/vi-vn/icon_bkcard_1028.jpg'},
        {name: 'ABBank', logo: 'Areas/Mobile/Content/Images/vi-vn/icon_bkcard_1029.jpg'},
        {name: 'AGRIBANK', logo: 'Areas/Mobile/Content/Images/vi-vn/icon_bkcard_1030.jpg'},
        {name: 'BaoViet Bank', logo: 'Areas/Mobile/Content/Images/vi-vn/icon_bkcard_1031.jpg'},
        {name: 'KienLong Bank', logo: 'Areas/Mobile/Content/Images/vi-vn/icon_bkcard_1032.jpg'},
        {name: 'LienVietPost Bank', logo: 'Areas/Mobile/Content/Images/vi-vn/icon_bkcard_1033.jpg'},
        {name: 'SAIGONBank', logo: 'Areas/Mobile/Content/Images/vi-vn/icon_bkcard_1034.jpg'},
        {name: 'SHB', logo: 'Areas/Mobile/Content/Images/vi-vn/icon_bkcard_1035.jpg'},
        {name: 'SHINHAN BANK', logo: 'Areas/Mobile/Content/Images/vi-vn/icon_bkcard_1036.jpg'},
    ]
}
